services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest  
    ports:
      - "80:80"
    volumes:
      - ./dist:/app
      - ./conf:/etc/nginx/conf.d

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
